---
name: Build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      DEBIAN_FRONTEND: noninteractive
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install cmake g++ libgtest-dev ninja-build
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: Configure
        run: |
          cmake \
            -Bbuild \
            -DCMAKE_BUILD_TYPE=Release \
            -GNinja 
      - name: Build
        run: ninja -Cbuild -v
      - name: Test
        run: ninja -Cbuild -v test
      - name: Upload executable
        uses: actions/upload-artifact@v3
        with:
          name: fun-cli
          path: build/fun-cli
